name: Resume Upload to Azure
# Based on https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-static-site-github-actions?tabs=userlevel

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_SP_GITHUBACTIONSFORRESUME }}

    - name: Upload to blob storage
      uses: azure/CLI@v2
      with:
        inlineScript: |
            az storage blob sync --account-name ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }} --destination '$web' --source .
    - name: Purge CDN endpoint
      uses: azure/CLI@v2
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name ${{ vars.AZURE_ENDPOINT_CDN_PROFILE_NAME }} --name ${{ vars.AZURE_ENDPOINT_NAME }} --resource-group ${{ vars.AZURE_ENDPOINT_RESOURCE_GROUP }}
  
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
